### ISSUE TITLE
Create more meaningful error messages

### ISSUE THREAD

**Issue by sinarueeger** [zkutalik/ssimp_software#65]
Currently, error messages are cryptic: exit codes (e.g. `Exited with exit code 134.`) or error messages (e.g. `WARNING: Ignoring this line, problem with the chromosome and/or position [SNPname:xx], Can't parse this double [NA]` or `file_reading::GwasFileHandle_NONCONST): Assertion `map_of_ref_records_of_tags.size() == tag_its_.size()' failed.`). 

The goal is, to return meaningful error messages, so that the user can take action.

**Comment by aaronmcdaid** [comment]
One of the errors was caused by a GWAS entry that had the same value (`na`) as the ref and alt allele. Ideally, we would delete these at the start, and warn the user about how many have been deleted. Also, we could take the same approach if `NA` has been recorded as the effect size
