### ISSUE TITLE
Inconsistent location for the build database

### ISSUE THREAD

**Issue by aaronmcdaid** [zkutalik/ssimp_software#66]
There are two different URLs for the build database.

https://drive.switch.ch/index.php/s/uOyjAtdvYjxxwZd/download is the correct one I think, but the README says https://drive.switch.ch/index.php/s/fcqrO9HWcINS2Qq/download

We should check this and ensure that only one (correct!) URL is in the software

We can run `git grep` to find these lines:

    git grep -o 'https://drive.switch.ch[^ ]*'

**Comment by aaronmcdaid** [comment]
Pull request is related to fixing this: #67

**Comment by sinarueeger** [comment]
Thanks @aaronmcdaid
