### ISSUE TITLE
Document version changes

### ISSUE THREAD

**Issue by sinarueeger** [zkutalik/ssimp_software#73]
Document the version changes from 0.4 to 0.5 in the [VERSION](https://github.com/zkutalik/ssimp_software/blob/master/VERSION) file?

**Comment by sinarueeger** [comment]
@aaronmcdaid : do you have time to do this?

**Comment by aaronmcdaid** [comment]
Not yet. I'm in Ireland now for a long weekend of Gaelic football. Back in
Berlin on Sunday

Aaron

**Comment by sinarueeger** [comment]
Thank you! Enjoy the games!
