### ISSUE TITLE
reference panels (or other files) should not have to be in a user's home directory

### ISSUE THREAD

**Issue by Jeremy37** [zkutalik/ssimp_software#91]
I am only allowed a few Gb in my home directory, but have plenty of space elsewhere on our computing cluster.
It seems that for SSimp to run, it assumes that some files will be located in a user's home directory, e.g. ~/reference_panels/database.of.builds.1kg.uk10k.hrc.2018.01.18.bin.

The software should not require a specific location like this for such a large file.

**Comment by aaronmcdaid** [comment]
Hi Jeremy,
Using [symbolic links](https://en.wikipedia.org/wiki/Symbolic_link) it is possible to work around this issue. Imagine that `/large/disk` is a path to a location on your cluster that has lots of free disk space.

````
     rm -r ~/reference_panels                                        # delete the existing reference panel folder that you might have already downloaded
     mkdir -p /large/disk/reference_panels_for_ssimp                 # create an empty folder on your large disk
     ln -s /large/disk/reference_panels_for_ssimp ~/reference_panels # create the symbolic link
````

If you execute these lines, then `~/reference_panels` will be a symbolic link to the folder on your large disk. `ssimp` can then download large files to that folder.

If you have further questions, I can help, and also there might be other solutions to this problem

(I also hope to respond to the other issue that you reported in the next few days)
Aaron
